# This file was generated by GoReleaser. DO NOT EDIT.
cask "alchemist" do
  version "0.3.0"

  on_macos do
    sha256 "67f0e8b4778423e399a037bfd6be8557da2b85cb5d717096611cd217ca587da8"
    url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "4c53080eb8b3c9aa69c9467a6da894eae729d584b9b9a45c7e97d4e1b0ffe1af"
      url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3e59544949ca99d8ddb0e22e435d0477aedca0196aeb1208689575b178bd1c9"
      url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_linux_arm64.tar.gz"
    end
  end

  name "alchemist"
  desc "Keyboard-driven terminal IDE for Azure Cosmos DB"
  homepage "https://github.com/colbytimm/Alchemist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alchemist"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alchemist"]
    end
  end

  # No zap stanza required

end
