# This file was generated by GoReleaser. DO NOT EDIT.
cask "alchemist" do
  version "0.3.2"

  on_macos do
    sha256 "d144b03c84740180545be93554320f62d3c3a0d2c00d3bdaa797f45d6eb3d917"
    url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "72b64bc2d97590bb481d069987c13c4aa99f3a2acf7054e95afb3cb196237c7f"
      url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "850be45209d2e37e8b9d163a6170246af7c2db5bf5b51443916cdfdc7ab19bae"
      url "https://github.com/colbytimm/Alchemist/releases/download/v#{version}/alchemist_#{version}_linux_arm64.tar.gz"
    end
  end

  name "alchemist"
  desc "Keyboard-driven terminal IDE for Azure Cosmos DB"
  homepage "https://github.com/colbytimm/Alchemist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "alchemist"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/alchemist"]
    end
  end

  # No zap stanza required

end
